server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///intelligent-course-system
      username: root
      password: "123456"

mybatis-plus:
  type-aliases-package: com.zephyrtoria.pojo